#ifndef SGBASICGEOMETRY_GLOBAL_H
#define SGBASICGEOMETRY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SGBASICGEOMETRY_LIB
# define SGBASICGEOMETRY_EXPORT Q_DECL_EXPORT
#else
# define SGBASICGEOMETRY_EXPORT Q_DECL_IMPORT
#endif

#endif // SGBASICGEOMETRY_GLOBAL_H
